use_frameworks!

platform :ios, '9.0'

target 'PHPageViewController_Example' do
  pod 'PHPageViewController', :path => '../'
  pod 'SnapKit'
  pod 'PHQRCode'
  target 'PHPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
